#!/bin/bash

rm home/david/pngs/*

if java -jar /home/david/ImageOps.jar $1 $2 $3 $4 $5 $6 $7 ; then
    rm /home/david/CSCI-440-Website/Website_combine/video.swf
    ffmpeg -f image2 -i /home/david/pngs/image%d.png /home/david/CSCI-440-Website/Website_combine/video.swf
fi
